export enum AlgoError {
    CLIENT_NOT_SET = 'CLIENT HAS NOT SET',
    BRIDGE_NOT_SET = 'BRIDGE HAS NOT SET',
    INVALID_ASSET = 'UNDEFINED ASSET',
    INVALID_ASSET_ID ='ASSED ID NOT FOUND',
    INVALID_ASSET_ID_TYPE ='ASSET ID SHOULD BE number',
    UNDEFINED_TRANSACTION = 'TRANSACTION IS UNDEFINED',
    INVALID_SIGNER ='SIGNER IS REQUIRED',
    MISSING_SECRET_KEY =' SIGNER SECRET KEY IS REQUIRED',
    UNDEFINED_ACCOUNTS ='ACCOUNTS NOT DEFINED',
    TIMEOUT ='TIMEOUT WAITING FOR BALANCE',
    POLLER_NOT_SET='POLLER NOT SET',
    INVALID_MNEMONIC =' MNEMONIC INVALID OR NOT DEFINED',
    ACCOUNT_INFO ='ACCOUNT INFO NOT FOUND',
    INVALID_ACCOUNT ='ACCOUNT/ADDRESS IS UNDEFINED',
    INDEXER_NOT_SET ='ALGO INDEXER IS NOT SET',
    INVALID_APP_ID ='APP ID NOT DEFINED'

  }

